trigger:
  batch: true
  branches:
    include:
    - release/6.x
    - release/9.x

pr:
  branches:
    include:
    - master

variables:
- ${{ if ne(variables['System.TeamProject'], 'public') }}:
  - group: DotNet-VSTS-Bot
  - group: DotNet-Blob-Feed
- ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
  # Variables used by arcade to publish packages
  - name: _DotNetFeedUrl
    value: https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
  - name: _DotNetValidationArtifactsCategory
    value: .NETCore
  - name: _DotNetArtifactsCategory
    value: .NETCore

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enablePublishBuildArtifacts: false
      enablePublishBuildAssets: false
      enablePublishUsingPipelines: false
      variables:
        - _BuildConfig: Release
      jobs:

      ############ LINUX BUILD ############
      - job: Build_Linux
        displayName: Linux
        timeoutInMinutes: 120
        strategy:
          matrix:
            x64:
              poolname: Hosted Ubuntu 1604
              assetManifestOS: linux
              assetManifestPlatform: x64
              installDependencies: true
        pool:
          name: $(poolname)
        steps:
        - bash: |
            git clean -ffdx
            git reset --hard HEAD
          displayName: 'Clean up working directory'

        - bash: |
            sudo apt update
            sudo apt -y install nuget libgdiplus build-essential libtool libtool-bin cmake gettext bc
          displayName: 'Install Linux dependencies'
          condition: and(succeeded(), eq(variables['installDependencies'], 'true'))

        - bash: |
            ./build.sh --ci -r -c $(_BuildConfig)
          displayName: 'Build (Make)'

        - bash: |
            ./build.sh --ci --pack
          displayName: 'Build nupkg'

#        - script: ./eng/common/build.sh --ci --restore --publish --configuration $(_BuildConfig) /p:DotNetPublishUsingPipelines=true /p:DotNetPublishToBlobFeed=true /p:DotNetPublishBlobFeedUrl=$(_DotNetFeedUrl) /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1) /p:DotNetArtifactsCategory=$(_DotNetArtifactsCategory) /p:AssetManifestOS=$(assetManifestOS) /p:PlatformName=$(assetManifestPlatform) --projects $(Build.SourcesDirectory)/eng/empty.csproj
#          displayName: Publish packages
#          condition: and(succeeded(), ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest'))

      ############ MACOS BUILD ############
      - job: Build_macOS
        displayName: macOS
        timeoutInMinutes: 120
        strategy:
          matrix:
            x64:
              poolname: Hosted macOS
              assetManifestOS: osx
              assetManifestPlatform: x64
        pool:
          name: $(poolname)
        steps:
        - bash: |
            git clean -ffdx
            git reset --hard HEAD
          displayName: 'Clean up working directory'

        - bash: |
            brew install autoconf automake libtool gnu-sed
          displayName: 'Prepare macOS dependencies'

        - bash: |
            ./build.sh --ci -r -c $(_BuildConfig)
          displayName: 'Build (Make)'

        - bash: |
            ./build.sh --ci --pack
          displayName: 'Build nupkg'

#        - script: ./eng/common/build.sh --ci --restore --publish --configuration $(_BuildConfig) /p:DotNetPublishUsingPipelines=true /p:DotNetPublishToBlobFeed=true /p:DotNetPublishBlobFeedUrl=$(_DotNetFeedUrl) /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1) /p:DotNetArtifactsCategory=$(_DotNetArtifactsCategory) /p:AssetManifestOS=$(assetManifestOS) /p:PlatformName=$(assetManifestPlatform) --projects $(Build.SourcesDirectory)/eng/empty.csproj
#          displayName: Publish packages
#          condition: and(succeeded(), ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest'))

      ############ WINDOWS BUILD ############
      - job: Build_Windows
        displayName: Windows
        timeoutInMinutes: 120
        strategy:
          matrix:
            x64:
              poolname: Hosted VS2017
              assetManifestOS: win
              assetManifestPlatform: x64
        pool:
          name: $(poolname)
        steps:
        - bash: |
            git clean -ffdx
            git reset --hard HEAD
          displayName: 'Clean up working directory'

        - script: |
            build.cmd --ci -r -c $(_BuildConfig)
          displayName: 'Build (MSBuild)'

#        - powershell: eng\common\build.ps1 -ci -restore -publish -configuration $(_BuildConfig) /p:DotNetPublishUsingPipelines=true /p:DotNetPublishToBlobFeed=true /p:DotNetPublishBlobFeedUrl=$(_DotNetFeedUrl) /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1) /p:DotNetArtifactsCategory=$(_DotNetArtifactsCategory) /p:AssetManifestOS=$(assetManifestOS) /p:PlatformName=$(assetManifestPlatform) -projects $(Build.SourcesDirectory)\eng\empty.csproj
#          displayName: Publish packages
#          condition: and(succeeded(), ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest'))

############ POST BUILD ARCADE LOGIC ############
#- ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
#  - template: /eng/common/templates/post-build/post-build.yml
#    parameters:
#      enableSourceLinkValidation: false
#      enableSigningValidation: false
#      enableSymbolValidation: false
#      enableNugetValidation: true
